In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
mpl.style.use('ggplot')

In [46]:
car=pd.read_csv('Originalcardata.csv')

In [47]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [48]:
car.shape

(892, 6)

In [49]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [50]:
# we use this to see the data is cline or not we open ever data and see the mistake ...
#car['Price'].unique()
car['year'].unique()
#car['kms_drive'].unique()
#car['fuel_type'].unique()
#car['name'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

PROBLEM FOUNT IN THE DATA

In [ ]:
#mistake in the data 

#1. As you can see, there are some issues in the **year** column because it contains unwanted values.

#2. You can also notice that there is an **“Ask for Price”** entry in the **price** column, which is incorrect.

#3. In the **kms_driven** column, there are errors such as the presence of “kms,” commas, and some invalid values.

#4. There are also errors in the **fuel_type** column, including null values.

#5. In the **name** column, there are inconsistencies in the car names. To make it simpler and more consistent, we will keep only the first three words of each car name.

CLEANING

In [52]:
backup=car.copy()

In [53]:
#1 in thsi we use string opration 
car=car[car['year'].str.isnumeric()]

In [54]:
#canvert into integer type
car['year']=car['year'].astype(int)

In [55]:
car=car[car['Price']!="Ask For Price"]

In [56]:
car['Price']=car['Price'].str.replace(',','').astype(int)

In [57]:
car['kms_driven']=car['kms_driven'].str.split().str.get(0).str.replace(',','')

In [58]:
car=car[car['kms_driven'].str.isnumeric()]

In [59]:
car['kms_driven']=car['kms_driven'].astype(int)

In [60]:
car=car[~car['fuel_type'].isna()]

In [61]:
car['name']=car['name'].str.split().str.slice(start=0,stop=3).str.join(' ')

In [62]:
car=car.reset_index(drop=True)

In [63]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [64]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 38.4+ KB

In [65]:
car.describe(include='all')

,name,company,year,Price,kms_driven,fuel_type
count,816,816,816.000000,8.160000e+02,816.000000,816
unique,254,25,NaN,NaN,NaN,3
top,Maruti Suzuki Swift,Maruti,NaN,NaN,NaN,Petrol
freq,51,221,NaN,NaN,NaN,428
mean,NaN,NaN,2012.444853,4.117176e+05,46275.531863,NaN
std,NaN,NaN,4.002992,4.751844e+05,34297.428044,NaN
min,NaN,NaN,1995.000000,3.000000e+04,0.000000,NaN
25%,NaN,NaN,2010.000000,1.750000e+05,27000.000000,NaN
50%,NaN,NaN,2013.000000,2.999990e+05,41000.000000,NaN
75%,NaN,NaN,2015.000000,4.912500e+05,56818.500000,NaN
max,NaN,NaN,2019.000000,8.500003e+06,400000.000000,NaN

In [66]:
car=car[car['Price']<6000000]

In [67]:
#store the cline data in this file 
car.to_csv('Cleaned Car.csv')

MODEL

In [68]:
x=car.drop(columns='Price')
y=car['Price']

In [69]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test=train_test_split(x,y, test_size=0.2)

In [70]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [71]:
ohe=OneHotEncoder()
ohe.fit(x[['name','company','fuel_type']])

OneHotEncoder()

In [72]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),remainder='passthrough')

In [73]:
lr=LinearRegression()

In [74]:
pipe=make_pipeline(column_trans,lr)

In [75]:
pipe.fit(x_train,y_train)

/Users/aryanrajkumar/ml_env/lib/python3.9/site-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [76]:
y_pred=pipe.predict(x_test)

In [77]:
y_pred

array([ 275064.0694267 ,  304976.47171988,  281465.58848476,
        283218.29294619,  422649.25541608,  241642.16921857,
        207379.1071185 ,  295647.01983006,  377184.94042484,
        578343.9131913 ,  472466.78458919,  367737.81798251,
        506104.28866847,  673138.74381436, 1097157.63191457,
        -62487.04069574,  717296.16461226,  533832.5948758 ,
        130543.09662637,  154094.1141804 ,  648350.12238555,
        258214.32176039, 1136230.06876962,  804063.99238867,
        354338.69764212,  613562.19759467,  257368.86522682,
        293106.32073489,  234677.22203895,   87816.0452446 ,
        473493.7575874 ,  280431.9384279 ,  199749.33624589,
        705502.8301935 ,  413145.70432925,  365132.11048554,
        379144.04618162,  454428.28503107,  203848.16906992,
        565821.16752914, 1476474.77054144,  445099.46603075,
        174040.63730195,  461664.80861303,   58231.5022018 ,
        416751.0014452 ,  421710.76410794,  448417.00624676,
        234508.72275628,  332675.96729413, -132432.49170136,
        -25381.20582829,  448199.08351974,  156247.03037113,
        417322.83779489,  621519.96226519,  300788.91085599,
        379240.82184364,  381009.33228633, -218516.23613562,
        370157.48627883,  194124.78902923,  572887.64107743,
        455691.53771968,  234552.36278504,  499378.58314958,
        309348.52064939,  525353.75747122,  392032.78356019,
        801346.32263288,  300293.07944146,  576207.73543091,
        244304.04655716,  569309.75961296,  325581.895744  ,
        743325.83486062,  529297.19213043,  509981.36358944,
        510369.63780914,  304138.91146468,  386704.6515647 ,
        141756.09247071,   64345.58352318,  710424.88048561,
        761670.26931706,  360914.82367404,  509764.70945315,
        717788.6733631 ,  925583.48297422,  502366.47994351,
         33877.02413654, 1202460.8544355 ,  281211.36857097,
        432462.27921969,  -50740.44623846,  176910.22516543,
        133352.14792129,  401899.27774434,  584714.80039525,
        654500.7329859 ,   73673.96204147,  306121.20360343,
        300297.61640413,  661423.65874365,  344223.16229069,
        409743.81838875,  296717.29222499,  313329.51861444,
        409989.90075992,  160324.0765876 ,  461847.40367325,
        261724.83857121,  717788.6733631 ,  323949.97238149,
        108632.49816969,  374770.06499328,  538107.54850128,
        567941.23682766,  661423.65874365,  357489.92592525,
       -127916.12082529,   67549.90571891,  226511.36324321,
        789543.46658871,  271223.52582994,  251695.79996483,
        267028.42076866,  299202.27785999,  283967.88019608,
        458480.5693797 , 1477987.09143142,  384147.98503713,
        211564.72712931,  586307.97197926, -117529.78578398,
        412031.5254679 ,   18300.78046224, -224112.16933203,
         37493.46539471,  463580.41327791,  320774.09851253,
        300293.07944146,  510011.935084  ,  414004.01691291,
         -4798.98376808,  162578.68665627,  217937.04624684,
        239847.97165835,  239338.28599098,  359748.91035877,
        362007.92305231,  767896.50973701,  247026.22415912,
         16609.03481273, -144114.99826699,  493631.76376766,
        413628.61481233,  243554.10629864,  193664.3857412 ,
        208255.20844661,  332451.26312342,  326597.72381046,
       1525893.96240497])

In [78]:
r2_score(y_test,y_pred)

0.6498319156768951

In [79]:
scores=[]
for i in range(1000):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(x_train,y_train)
    y_pred=pipe.predict(x_test)
    scores.append(r2_score(y_test,y_pred))

In [80]:
np.argmax(scores)

np.int64(433)

In [81]:
scores[np.argmax(scores)]

0.8456987064934159

In [82]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=i)
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(x_train,y_train)
y_pred=pipe.predict(x_test)
r2_score(y_test,y_pred)

0.592630890730194

In [83]:
import pickle

In [84]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [85]:
pipe.predict(
    pd.DataFrame(
        [['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']],
        columns=['name','company','year','kms_driven','fuel_type']
    )
)

array([431076.24797914])

In [86]:
pipe.steps[0][1].transformers[0][1].categories[0]

array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat Diesel',
       'Chevrolet Beat LS', 'Chevrolet Beat LT', 'Chevrolet Beat PS',
       'Chevrolet Cruze LTZ', 'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4',
       'Chevrolet Sail 1.2', 'Chevrolet Sail UVA', 'Chevrolet Spark',
       'Chevrolet Spark 1.0', 'Chevrolet Spark LS', 'Chevrolet Spark LT',
       'Chevrolet Tavera LS', 'Chevrolet Tavera Neo', 'Datsun GO T',
       'Datsun Go Plus', 'Datsun Redi GO', 'Fiat Linea Emotion',
       'Fiat Petra ELX', 'Fiat Punto Emotion', 'Force Motors Force',
       'Force Motors One', 'Ford EcoSport', 'Ford EcoSport Ambiente',
       'Ford EcoSport Titanium', 'Ford EcoSport Trend',
       'Ford Endeavor 4x4', 'Ford Fiesta', 'Ford Fiesta SXi', 'Ford Figo',
       'Ford Figo Diesel', 'Ford Figo Duratorq', 'Ford Figo Petrol',
       'Ford Fusion 1.4', 'Ford Ikon 1.3', 'Ford Ikon 1.6',
       'Hindustan Motors Ambassador', 'Honda Accord', 'Honda Amaze',
       'Honda Amaze 1.2', 'Honda Amaze 1.5', 'Honda Brio', 'Honda Brio V',
       'Honda Brio VX', 'Honda City', 'Honda City 1.5', 'Honda City SV',
       'Honda City VX', 'Honda City ZX', 'Honda Jazz S', 'Honda Jazz VX',
       'Honda Mobilio', 'Honda Mobilio S', 'Honda WR V', 'Hyundai Accent',
       'Hyundai Accent Executive', 'Hyundai Accent GLE',
       'Hyundai Accent GLX', 'Hyundai Creta', 'Hyundai Creta 1.6',
       'Hyundai Elantra 1.8', 'Hyundai Elantra SX', 'Hyundai Elite i20',
       'Hyundai Eon', 'Hyundai Eon D', 'Hyundai Eon Era',
       'Hyundai Eon Magna', 'Hyundai Eon Sportz', 'Hyundai Fluidic Verna',
       'Hyundai Getz', 'Hyundai Getz GLE', 'Hyundai Getz Prime',
       'Hyundai Grand i10', 'Hyundai Santro', 'Hyundai Santro AE',
       'Hyundai Santro Xing', 'Hyundai Sonata Transform', 'Hyundai Verna',
       'Hyundai Verna 1.4', 'Hyundai Verna 1.6', 'Hyundai Verna Fluidic',
       'Hyundai Verna Transform', 'Hyundai Verna VGT',
       'Hyundai Xcent Base', 'Hyundai Xcent SX', 'Hyundai i10',
       'Hyundai i10 Era', 'Hyundai i10 Magna', 'Hyundai i10 Sportz',
       'Hyundai i20', 'Hyundai i20 Active', 'Hyundai i20 Asta',
       'Hyundai i20 Magna', 'Hyundai i20 Select', 'Hyundai i20 Sportz',
       'Jaguar XE XE', 'Jaguar XF 2.2', 'Jeep Wrangler Unlimited',
       'Land Rover Freelander', 'Mahindra Bolero DI',
       'Mahindra Bolero Power', 'Mahindra Bolero SLE',
       'Mahindra Jeep CL550', 'Mahindra Jeep MM', 'Mahindra KUV100',
       'Mahindra KUV100 K8', 'Mahindra Logan', 'Mahindra Logan Diesel',
       'Mahindra Quanto C4', 'Mahindra Quanto C8', 'Mahindra Scorpio',
       'Mahindra Scorpio 2.6', 'Mahindra Scorpio LX',
       'Mahindra Scorpio S10', 'Mahindra Scorpio S4',
       'Mahindra Scorpio SLE', 'Mahindra Scorpio SLX',
       'Mahindra Scorpio VLX', 'Mahindra Scorpio Vlx',
       'Mahindra Scorpio W', 'Mahindra TUV300 T4', 'Mahindra TUV300 T8',
       'Mahindra Thar CRDe', 'Mahindra XUV500', 'Mahindra XUV500 W10',
       'Mahindra XUV500 W6', 'Mahindra XUV500 W8', 'Mahindra Xylo D2',
       'Mahindra Xylo E4', 'Mahindra Xylo E8', 'Maruti Suzuki 800',
       'Maruti Suzuki A', 'Maruti Suzuki Alto', 'Maruti Suzuki Baleno',
       'Maruti Suzuki Celerio', 'Maruti Suzuki Ciaz',
       'Maruti Suzuki Dzire', 'Maruti Suzuki Eeco',
       'Maruti Suzuki Ertiga', 'Maruti Suzuki Esteem',
       'Maruti Suzuki Estilo', 'Maruti Suzuki Maruti',
       'Maruti Suzuki Omni', 'Maruti Suzuki Ritz', 'Maruti Suzuki S',
       'Maruti Suzuki SX4', 'Maruti Suzuki Stingray',
       'Maruti Suzuki Swift', 'Maruti Suzuki Versa',
       'Maruti Suzuki Vitara', 'Maruti Suzuki Wagon', 'Maruti Suzuki Zen',
       'Mercedes Benz A', 'Mercedes Benz B', 'Mercedes Benz C',
       'Mercedes Benz GLA', 'Mini Cooper S', 'Mitsubishi Lancer 1.8',
       'Mitsubishi Pajero Sport', 'Nissan Micra XL', 'Nissan Micra XV',
       'Nissan Sunny', 'Nissan Sunny XL', 'Nissan Terrano XL',
       'Nissan X Trail', 'Renault Duster', 'Renault Duster 110',
       'Renault Duster 110PS', 'Renault Duster 85', 'Renault Duster 85PS',
       'Renault Duster RxL', 'Renault Kwid', 'Renault Kwid 1.0',
       'Renault Kwid RXT', 'Renault Lodgy 85', 'Renault Scala RxL',
       'Skoda Fabia', 'Skoda Fabia 1.2L', 'Skoda Fabia Classic',
       'Skoda Laura', 'Skoda Octavia Classic', 'Skoda Rapid Elegance',
       'Skoda Superb 1.8', 'Skoda Yeti Ambition', 'Tata Aria Pleasure',
       'Tata Bolt XM', 'Tata Indica', 'Tata Indica V2', 'Tata Indica eV2',
       'Tata Indigo CS', 'Tata Indigo LS', 'Tata Indigo LX',
       'Tata Indigo Marina', 'Tata Indigo eCS', 'Tata Manza',
       'Tata Manza Aqua', 'Tata Manza Aura', 'Tata Manza ELAN',
       'Tata Nano', 'Tata Nano Cx', 'Tata Nano GenX', 'Tata Nano LX',
       'Tata Nano Lx', 'Tata Sumo Gold', 'Tata Sumo Grande',
       'Tata Sumo Victa', 'Tata Tiago Revotorq', 'Tata Tiago Revotron',
       'Tata Tigor Revotron', 'Tata Venture EX', 'Tata Vista Quadrajet',
       'Tata Zest Quadrajet', 'Tata Zest XE', 'Tata Zest XM',
       'Toyota Corolla', 'Toyota Corolla Altis', 'Toyota Corolla H2',
       'Toyota Etios', 'Toyota Etios G', 'Toyota Etios GD',
       'Toyota Etios Liva', 'Toyota Fortuner', 'Toyota Fortuner 3.0',
       'Toyota Innova 2.0', 'Toyota Innova 2.5', 'Toyota Qualis',
       'Volkswagen Jetta Comfortline', 'Volkswagen Jetta Highline',
       'Volkswagen Passat Diesel', 'Volkswagen Polo',
       'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
       'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
       'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
       'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object)